Controllers/PortfolioController.cs
using ArtCulture.Models;
using ArtCulture.Service;
using ArtCulture.Service.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace ArtCulture.Controllers
{
    [Route("[controller]")]
    public class PortfolioController : Controller
    {
        List<Portfolio> listaPortfolio = new List<Portfolio>();
        private readonly IPortfolioService _portfolioService;
        public PortfolioController(
            IPortfolioService portfolioService
            )
        {
            _portfolioService = portfolioService;

        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpGet("Portfolio/Portfolio")]
        public IActionResult Portfolio()
        {
           var listaPortifolio = ListaPortfolio();
           ViewBag.Portfolio = listaPortifolio.Resultado;

            
            return View();
        }

        [HttpGet("Portfolio/CadastrarPortfolio")]
        public IActionResult CadastrarPortfolio()
        {
            return View();
        }

        [HttpGet("Portfolio/EditarPortfolio")]
        public IActionResult EditarPortfolio(int Id)
        {
            
            var portfolioAntigo = _portfolioService.SelecionarPorId(Id);
            ViewBag.PortfolioAntigo = portfolioAntigo.Resultado;
            
           
            return View();
        }

        [HttpGet("Portfolio/Produto")]
        public IActionResult Produto()
        {
            return View();
        }
        [HttpGet("Portfolio/Servico")]
        public IActionResult Servico()
        {
            return View();
        }
        public IActionResult Test()
        {
            return View();
        }


        [HttpGet("CadastrarPortfolio")]
        public ActionResult CadastrarAmigo()
        {
            return View();
        }

        [HttpPost("Portfolio/Portfolio/CadastrarPortfolio")]
        public ActionResult CadastrarPortfolio(Portfolio portfolio)
        {
            var usuarioLogado = JsonConvert.DeserializeObject<IList<Usuario>>(HttpContext.Session.GetString("usuarioLogado"));
            ViewBag.UsuarioLogado = usuarioLogado;

            var resposta = _portfolioService.CadastrarPortfolio(portfolio, usuarioLogado[0]);
            return Redirect("/Portfolio/Portfolio/Portfolio");
            //return View(portfolio);
        }

        [HttpPost]
        public ActionResult CadastrarProduto(Produto produto)
        {
            var resposta = _portfolioService.CadastrarProduto(produto);
            return View(produto);
        }

        [HttpPost]
        public ActionResult CadastrarServico(Servico servico)
        {
            var resposta = _portfolioService.CadastrarServico(servico);
            return View(servico);
        }

        [HttpGet("Portfolio/Portfolio/Listar")]
        public Resposta<Portfolio> ListaPortfolio()
        {
            var resposta = _portfolioService.ListarPortfolio();
            return resposta;
        }

        [HttpGet("Portfolio/Produto/Listar")]
        public ActionResult ListaProduto(Produto produto)
        {
            var resposta = _portfolioService.CadastrarProduto(produto);
            return View(produto);
        }

        [HttpGet("Portfolio/Servico/Listar")]
        public ActionResult ListarServico(Servico servico)
        {
            var resposta = _portfolioService.CadastrarServico(servico);
            return View(servico);
        }

        [HttpGet("Portfolio/Excluir")]
        public ActionResult ExcluirPortfolio(int Id)
        {
            var resposta = _portfolioService.ExcluirPortfolio(Id);
            return Redirect("/Portfolio/Portfolio/Portfolio");
        }

        [HttpPost("Portfolio/Editar")]
        public ActionResult EditarPortfolio(Portfolio portfolio)
        {

            var resposta = _portfolioService.AlterarPortfolio(portfolio);
            return Redirect("/Portfolio/Portfolio/Portfolio");
        }

    }
}
        

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LabEducacional</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>  
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LabEducacional</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                         <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Portfolio" asp-action="Servico"> Serviços </a>
                        </li>

                         <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Portfolio" asp-action="Portfolio"> Portfolio </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Portfolio" asp-action="Produto"> Produtos </a>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <div class="row" style="padding:15px;">

        <div class="col-lg-6">
            <a href="Usuario/login"><button type="button" class="btn btn-block btn-dark">
                Entrar no Sistema
            </button></a>
        </div>

        <div class="col-lg-6">
            <a href="Usuario/registrar"><button type="button" class="btn btn-block btn-dark">
                Registrar no Sistema
            </button></a>
        </div>

    </div>

    <footer class="border-top footer text-muted" style="background-color:black">
        <div class="container">
            &copy; 2022 - LabEducacional - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>